### ISSUE TITLE
Python3.x compatibility? 

### ISSUE THREAD

**Issue by evanbiederstedt** [MicrosoftGenomics/PySnpTools#4]
Naturally, at the moment this cannot be installed with Python3.4 and Python3.5

How difficult would it be to make it Python3.x compatible?

**Comment by davek44** [comment]
I would be interested in a python3 version, too.

**Comment by p-himik** [comment]
I've created a PR #7 for this

**Comment by CarlKCarlK** [comment]
’m happy to report that we’ve just released PySnpTools for Python 3! Just “pip install pysnptools”.
See https://pypi.org/project/pysnptools for details.
Everything from code & notebooks to API examples now runs on both Python 2.7+ and Python 3.7+.
Thanks for using PySnpTools.
